# Generated by Django 5.0.4 on 2024-04-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_performanceone_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancetwo',
            name='attitude_and_effort',
            field=models.CharField(choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='customer_service',
            field=models.CharField(choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='health_and_safety',
            field=models.CharField(choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='knowledge_and_skill_improvement',
            field=models.CharField(choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='reliability_and_time_management',
            field=models.CharField(choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='teamwork',
            field=models.CharField(choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='working_under_pressure',
            field=models.CharField(choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
    ]
