# Generated by Django 5.0.4 on 2024-04-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_how_well_they_think_they_are_doing_on_the_job_performanceone_how_well_do_you_think_you_are_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancetwo',
            name='attitude_and_effort_comment',
            field=models.CharField(default='test', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetwo',
            name='customer_service_comment',
            field=models.CharField(default='test', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetwo',
            name='health_and_safety_comment',
            field=models.CharField(default='test', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetwo',
            name='knowledge_and_skill_improvement_comment',
            field=models.CharField(default='test', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetwo',
            name='reliability_and_time_management_comment',
            field=models.CharField(default='test', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetwo',
            name='teamwork_comment',
            field=models.CharField(default='test', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetwo',
            name='working_under_pressure_comment',
            field=models.CharField(default='test', max_length=10000),
            preserve_default=False,
        ),
    ]
