# Generated by Django 5.0.4 on 2024-04-30 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_performancetwo_attitude_and_effort_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceone',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancetwo',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
            preserve_default=False,
        ),
    ]
