# Generated by Django 5.0.4 on 2024-05-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_performanceone_staff_performancetwo_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancetwo',
            name='attitude_and_effort',
            field=models.CharField(blank=True, choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='attitude_and_effort_comment',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='customer_service',
            field=models.CharField(blank=True, choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='customer_service_comment',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='health_and_safety',
            field=models.CharField(blank=True, choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='health_and_safety_comment',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='knowledge_and_skill_improvement',
            field=models.CharField(blank=True, choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='knowledge_and_skill_improvement_comment',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='reliability_and_time_management',
            field=models.CharField(blank=True, choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='reliability_and_time_management_comment',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='teamwork',
            field=models.CharField(blank=True, choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='teamwork_comment',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='working_under_pressure',
            field=models.CharField(blank=True, choices=[('Unsatifactory', 'Unsatifactory'), ('Below Expectations', 'Below Expectations'), ('Meets Expectations', 'Meets Expectations'), ('Exceeds Expectations', 'Exceeds Expectations'), ('Outstanding', 'Outstanding')], max_length=100),
        ),
        migrations.AlterField(
            model_name='performancetwo',
            name='working_under_pressure_comment',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
