# Generated by Django 5.0.4 on 2024-05-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_performancetwo_attitude_and_effort_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceone',
            old_name='are_you_aware_of_what_you_need_to_do_to_achieve_these_goals',
            new_name='q1',
        ),
        migrations.RenameField(
            model_name='performanceone',
            old_name='do_you_feel_you_have_achieved_the_goals_you_set_last_year',
            new_name='q2',
        ),
        migrations.RenameField(
            model_name='performanceone',
            old_name='explain_how_you_have_or_why_you_have_managed_to_achieve_these_goals',
            new_name='q3',
        ),
        migrations.RenameField(
            model_name='performanceone',
            old_name='how_do_you_feel_about_your_job_and_the_company',
            new_name='q4',
        ),
        migrations.RenameField(
            model_name='performanceone',
            old_name='how_well_do_you_think_you_are_doing_on_the_job',
            new_name='q5',
        ),
        migrations.RenameField(
            model_name='performanceone',
            old_name='is_there_any_equipment_or_training_to_help_you_in_your_role',
            new_name='q6',
        ),
        migrations.RenameField(
            model_name='performanceone',
            old_name='what_are_your_achievable_goals_for_the_next_12_months',
            new_name='q7',
        ),
        migrations.RenameField(
            model_name='performanceone',
            old_name='what_would_you_change_if_you_could',
            new_name='q8',
        ),
        migrations.RenameField(
            model_name='performanceone',
            old_name='which_parts_of_your_job_are_doing_well_and_where_do_you_think_you_could_improve',
            new_name='q9',
        ),
    ]
