# Generated by Django 5.0.4 on 2024-05-02 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_are_you_aware_of_what_you_need_to_do_to_achieve_these_goals_performanceone_q1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='created_at_nz',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
